"""Add telefono, email, direccion to especialistas

Revision ID: adfaa079db19
Revises: fe85c99eb3f8
Create Date: 2025-08-25 11:28:02.410102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfaa079db19'
down_revision: Union[str, Sequence[str], None] = 'fe85c99eb3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('esp_especialistas', sa.Column('esp_telefono', sa.String(length=255), nullable=True))
    op.add_column('esp_especialistas', sa.Column('esp_email', sa.String(length=255), nullable=True))
    op.add_column('esp_especialistas', sa.Column('esp_direccion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('esp_especialistas', 'esp_direccion')
    op.drop_column('esp_especialistas', 'esp_email')
    op.drop_column('esp_especialistas', 'esp_telefono')
    # ### end Alembic commands ###
